# CSV PRACTICE PROBLEMS

In [10]:
import pandas as pd
import numpy as np
from IPython.display import display

In [13]:
students_df = pd.read_csv("Students.csv")

top_student = students_df.loc[students_df["Marks"].idxmax()]
print("Student with highest marks:")
print(top_student)

passed_students = students_df[students_df["Result"] == "Pass"]
passed_students.to_csv("PassedStudents.csv", index=False)

print("\nPassed students written to PassedStudents.csv")
display(passed_students)

Student with highest marks:
Student Name    Ananya Rao
USN                 USN006
Department             CSE
Marks                   95
Result                Pass
Name: 5, dtype: object

Passed students written to PassedStudents.csv

   Student Name     USN Department  Marks Result
0   Aarav Kumar  USN001        CSE     88   Pass
1  Meera Sharma  USN002        ECE     92   Pass
2     Rohan Das  USN003         ME     76   Pass
3    Priya Nair  USN004        CSE     65   Pass
5    Ananya Rao  USN006        CSE     95   Pass
6   Karan Patel  USN007         IT     81   Pass
8  Aditya Menon  USN009         ME     89   Pass
9    Neha Verma  USN010        CSE     72   Pass

In [22]:
import csv

emdf = pd.read_csv("Employees.csv")
# display(emdf)

# Step 2: Read and find employee with maximum salary
print(emdf.loc[emdf["Salary"].idxmax()])

# # Step 3: Write IT department employees to ITEmployees.csv
it_emdf = emdf[emdf["Department"] == "IT"]
display(it_emdf)

it_emdf.to_csv("ITEmployees.csv")

Employee ID    Ananya Rao
Name               USN006
Department            CSE
Salary                 95
City                 Pass
Name: 5, dtype: object

   Employee ID    Name Department  Salary  City
6  Karan Patel  USN007         IT      81  Pass